global:
  scrape_intervar: 15s

  extarnal_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheous'

    scpare_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'booking'

    scpare_interval: 5s

    static_configs:
      - targets: ['booking:9090']